2024-12-08 11:46:40,134 INFO    MainThread:15 [wandb_setup.py:_flush():79] Current SDK version is 0.18.5
2024-12-08 11:46:40,134 INFO    MainThread:15 [wandb_setup.py:_flush():79] Configure stats pid to 15
2024-12-08 11:46:40,134 INFO    MainThread:15 [wandb_setup.py:_flush():79] Loading settings from /root/.config/wandb/settings
2024-12-08 11:46:40,134 INFO    MainThread:15 [wandb_setup.py:_flush():79] Loading settings from /app2/Milestone 3/training/wandb/settings
2024-12-08 11:46:40,134 INFO    MainThread:15 [wandb_setup.py:_flush():79] Loading settings from environment variables: {}
2024-12-08 11:46:40,134 INFO    MainThread:15 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2024-12-08 11:46:40,134 INFO    MainThread:15 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program_relpath': 'training_script_2.py', 'program_abspath': '/app2/Milestone 3/training/training_script_2.py', 'program': '/app2/Milestone 3/training/training_script_2.py'}
2024-12-08 11:46:40,134 INFO    MainThread:15 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-12-08 11:46:40,134 INFO    MainThread:15 [wandb_setup.py:_flush():79] Applying login settings: {'api_key': '***REDACTED***'}
2024-12-08 11:46:40,134 INFO    MainThread:15 [wandb_init.py:_log_setup():534] Logging user logs to /app2/Milestone 3/training/wandb/run-20241208_114640-8qbnir7v/logs/debug.log
2024-12-08 11:46:40,134 INFO    MainThread:15 [wandb_init.py:_log_setup():535] Logging internal logs to /app2/Milestone 3/training/wandb/run-20241208_114640-8qbnir7v/logs/debug-internal.log
2024-12-08 11:46:40,134 INFO    MainThread:15 [wandb_init.py:init():621] calling init triggers
2024-12-08 11:46:40,134 INFO    MainThread:15 [wandb_init.py:init():628] wandb.init called with sweep_config: {}
config: {}
2024-12-08 11:46:40,134 INFO    MainThread:15 [wandb_init.py:init():671] starting backend
2024-12-08 11:46:40,134 INFO    MainThread:15 [wandb_init.py:init():675] sending inform_init request
2024-12-08 11:46:40,138 INFO    MainThread:15 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-12-08 11:46:40,138 INFO    MainThread:15 [wandb_init.py:init():688] backend started and connected
2024-12-08 11:46:40,145 INFO    MainThread:15 [wandb_init.py:init():783] updated telemetry
2024-12-08 11:46:40,149 INFO    MainThread:15 [wandb_init.py:init():816] communicating run to backend with 90.0 second timeout
2024-12-08 11:46:40,348 ERROR   MainThread:15 [wandb_init.py:init():842] encountered error: failed to upsert bucket: returned error 404 Not Found: {"errors":[{"message":"entity bme_deeepl_learning not found during upsertBucket","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-12-08 11:46:40,348 ERROR   MainThread:15 [wandb_init.py:init():1266] error in wandb.init()
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1256, in init
    return wi.init()
           ^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 848, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 404 Not Found: {"errors":[{"message":"entity bme_deeepl_learning not found during upsertBucket","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-12-08 11:46:40,360 WARNING MsgRouterThr:15 [router.py:message_loop():77] message_loop has been closed
